services:
  - type: web
    name: sandipan-portfolio
    env: docker
    repo: https://github.com/Sandip-2005/Sandipan_Bhunia.git
    branch: main
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: APP_NAME
        value: "Sandipan Bhunia Portfolio"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: log
      - key: DB_CONNECTION
        value: pgsql